from django.urls import path

from shop.cms import (
    IndexView as CmsIndexView, CategoryListView, CategoryDetailView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    TagListView, TagDetailView, TagCreateView, TagUpdateView, TagDeleteView,
    AttributeListView, AttributeDetailView, AttributeCreateView,
    AttributeUpdateView, AttributeDeleteView,
    SupplierListView, SupplierDetailView, SupplierCreateView,
    SupplierUpdateView, SupplierDeleteView, WareHouseListView,
    WareHouseDetailView, WareHouseCreateView, WareHouseUpdateView,
    WareHouseDeleteView, BrandListView, BrandDetailView, BrandCreateView,
    BrandUpdateView, BrandDeleteView, FeatureListView, FeatureDetailView,
    FeatureCreateView, FeatureUpdateView, FeatureDeleteView, ProductListView,
    ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView,
    ShipmentListView, ShipmentDetailView, ShipmentCreateView,
    ShipmentUpdateView, ShipmentDeleteView, HeroListView, HeroDetailView,
    HeroCreateView, HeroUpdateView, HeroDeleteView, OfferListView,
    OfferDetailView, OfferCreateView, OfferUpdateView, OfferDeleteView,
    AddressListView, AddressDetailView, AddressCreateView, AddressUpdateView,
    AddressDeleteView, OrderListView as CmsOrderListView, OrderDetailView,
    OrderCreateView, OrderUpdateView, OrderDeleteView,
    model_order
)

from .views import (
    IndexView, CatalogListView,
    CatalogProductDetailView, OrderListView, BasketView,
    OrderFormView, AddressCreateView as SiteAddressCreateView,
    AddressUpdateView as SiteAddressUpdateView,
    AddressDeleteView as SiteAddressDeleteView,
    search_items,
)

from .functions import (
    remove_from_basket, add_to_basket, clear_basket,
    remove_item_from_basket
)


app_name = 'shop'
urlpatterns = [
    path('cms/', CmsIndexView.as_view(), name='cms-index'),
    path('cms/categories/',
         CategoryListView.as_view(), name='category-list'),
    path('cms/categories/add/',
         CategoryCreateView.as_view(), name='category-create'),
    path('cms/categories/<int:pk>/',
         CategoryDetailView.as_view(), name='category-detail'),
    path('cms/categories/update/<int:pk>/',
         CategoryUpdateView.as_view(), name='category-update'),
    path('cms/categories/delete/<int:pk>/',
         CategoryDeleteView.as_view(), name='category-delete'),

    path('cms/tags/',
         TagListView.as_view(), name='tag-list'),
    path('cms/tags/add/',
         TagCreateView.as_view(), name='tag-create'),
    path('cms/tags/<int:pk>/',
         TagDetailView.as_view(), name='tag-detail'),
    path('cms/tags/update/<int:pk>/',
         TagUpdateView.as_view(), name='tag-update'),
    path('cms/tags/delete/<int:pk>/',
         TagDeleteView.as_view(), name='tag-delete'),

    path('cms/attributes/',
         AttributeListView.as_view(), name='attribute-list'),
    path('cms/attributes/add/',
         AttributeCreateView.as_view(), name='attribute-create'),
    path('cms/attributes/<int:pk>/',
         AttributeDetailView.as_view(), name='attribute-detail'),
    path('cms/attributes/update/<int:pk>/',
         AttributeUpdateView.as_view(), name='attribute-update'),
    path('cms/attributes/delete/<int:pk>/',
         AttributeDeleteView.as_view(), name='attribute-delete'),

    path('cms/suppliers/',
         SupplierListView.as_view(), name='supplier-list'),
    path('cms/suppliers/add/',
         SupplierCreateView.as_view(), name='supplier-create'),
    path('cms/suppliers/<int:pk>/',
         SupplierDetailView.as_view(), name='supplier-detail'),
    path('cms/suppliers/update/<int:pk>/',
         SupplierUpdateView.as_view(), name='supplier-update'),
    path('cms/suppliers/delete/<int:pk>/',
         SupplierDeleteView.as_view(), name='supplier-delete'),

    path('cms/warehouses/',
         WareHouseListView.as_view(), name='warehouse-list'),
    path('cms/warehouses/add/',
         WareHouseCreateView.as_view(), name='warehouse-create'),
    path('cms/warehouses/<int:pk>/',
         WareHouseDetailView.as_view(), name='warehouse-detail'),
    path('cms/warehouses/update/<int:pk>/',
         WareHouseUpdateView.as_view(), name='warehouse-update'),
    path('cms/warehouses/delete/<int:pk>/',
         WareHouseDeleteView.as_view(), name='warehouse-delete'),

    path('cms/brands/',
         BrandListView.as_view(), name='brand-list'),
    path('cms/brands/add/',
         BrandCreateView.as_view(), name='brand-create'),
    path('cms/brands/<int:pk>/',
         BrandDetailView.as_view(), name='brand-detail'),
    path('cms/brands/update/<int:pk>/',
         BrandUpdateView.as_view(), name='brand-update'),
    path('cms/brands/delete/<int:pk>/',
         BrandDeleteView.as_view(), name='brand-delete'),

    path('cms/features/',
         FeatureListView.as_view(), name='feature-list'),
    path('cms/features/add/',
         FeatureCreateView.as_view(), name='feature-create'),
    path('cms/features/<int:pk>/',
         FeatureDetailView.as_view(), name='feature-detail'),
    path('cms/features/update/<int:pk>/',
         FeatureUpdateView.as_view(), name='feature-update'),
    path('cms/features/delete/<int:pk>/',
         FeatureDeleteView.as_view(), name='feature-delete'),

    path('cms/products/',
         ProductListView.as_view(), name='product-list'),
    path('cms/products/add/',
         ProductCreateView.as_view(), name='product-create'),
    path('cms/products/<int:pk>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('cms/products/update/<int:pk>/',
         ProductUpdateView.as_view(), name='product-update'),
    path('cms/products/delete/<int:pk>/',
         ProductDeleteView.as_view(), name='product-delete'),

    path('cms/shipments/',
         ShipmentListView.as_view(), name='shipment-list'),
    path('cms/shipments/add/',
         ShipmentCreateView.as_view(), name='shipment-create'),
    path('cms/shipments/<int:pk>/',
         ShipmentDetailView.as_view(), name='shipment-detail'),
    path('cms/shipments/update/<int:pk>/',
         ShipmentUpdateView.as_view(), name='shipment-update'),
    path('cms/shipments/delete/<int:pk>/',
         ShipmentDeleteView.as_view(), name='shipment-delete'),

    path('cms/heroes/',
         HeroListView.as_view(), name='hero-list'),
    path('cms/heroes/add/',
         HeroCreateView.as_view(), name='hero-create'),
    path('cms/heroes/<int:pk>/',
         HeroDetailView.as_view(), name='hero-detail'),
    path('cms/heroes/update/<int:pk>/',
         HeroUpdateView.as_view(), name='hero-update'),
    path('cms/heroes/delete/<int:pk>/',
         HeroDeleteView.as_view(), name='hero-delete'),

    path('cms/offers/',
         OfferListView.as_view(), name='offer-list'),
    path('cms/offers/add/',
         OfferCreateView.as_view(), name='offer-create'),
    path('cms/offers/<int:pk>/',
         OfferDetailView.as_view(), name='offer-detail'),
    path('cms/offers/update/<int:pk>/',
         OfferUpdateView.as_view(), name='offer-update'),
    path('cms/offers/delete/<int:pk>/',
         OfferDeleteView.as_view(), name='offer-delete'),

    path('cms/address/',
         AddressListView.as_view(), name='address-list'),
    path('cms/address/add/',
         AddressCreateView.as_view(), name='address-create'),
    path('cms/address/<int:pk>/',
         AddressDetailView.as_view(), name='address-detail'),
    path('cms/address/update/<int:pk>/',
         AddressUpdateView.as_view(), name='address-update'),
    path('cms/address/delete/<int:pk>/',
         AddressDeleteView.as_view(), name='address-delete'),

    path('cms/orders/',
         CmsOrderListView.as_view(), name='order-list'),
    path('cms/orders/add/',
         OrderCreateView.as_view(), name='order-create'),
    path('cms/orders/<int:pk>/',
         OrderDetailView.as_view(), name='order-detail'),
    path('cms/orders/update/<int:pk>/',
         OrderUpdateView.as_view(), name='order-update'),
    path('cms/orders/delete/<int:pk>/',
         OrderDeleteView.as_view(), name='order-delete'),
    path('cms/model/order/', model_order, name='model-order'),
]

urlpatterns += [
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('catalog/<int:pk>/', CatalogProductDetailView.as_view(),
         name='catalog-product-detail'),
    path('basket/items/', BasketView.as_view(), name='basket'),
    path('address/create/', SiteAddressCreateView.as_view(),
         name='site-address-add'),
    path('address/<int:pk>/update/', SiteAddressUpdateView.as_view(),
         name='site-address-update'),
    path('address/<int:pk>/delete/', SiteAddressDeleteView.as_view(),
         name='site-address-delete'),
    path('myorders/items/', OrderListView.as_view(), name='myorders'),
    path('remove_from_basket/<int:id>/', remove_from_basket,
         name='remove_from_basket'),
    path('add_to_basket/<int:id>/', add_to_basket, name='add_to_basket'),
    path('remove_item_from_basket/<int:id>/', remove_item_from_basket,
         name='remove_item_from_basket'),
    path('clear/basket', clear_basket, name='clear-basket'),
    path('order/items/', OrderFormView.as_view(), name='order'),
    path('search/', search_items, name="search"),
]
