# Generated by Django 3.0.8 on 2020-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
