# Generated by Django 3.1.3 on 2020-12-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_offer_offerdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='is_published',
        ),
    ]
