# Generated by Django 3.1.3 on 2020-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201204_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/logos'),
        ),
        migrations.AddField(
            model_name='category',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='category/heroes'),
        ),
        migrations.AddField(
            model_name='product',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='product/heroes'),
        ),
    ]
