# Generated by Django 3.1.3 on 2020-12-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201204_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='productmedia/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productmedia', to='products.product')),
            ],
            options={
                'verbose_name': 'product media',
                'verbose_name_plural': 'product media',
                'default_related_name': 'productmedia',
            },
        ),
    ]
