# Generated by Django 3.1.3 on 2020-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='media_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='specification_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
