# Generated by Django 3.1.3 on 2020-12-04 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_offerdetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('shipment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productshipment', to='products.product')),
            ],
            options={
                'verbose_name': 'product shipments',
                'verbose_name_plural': 'product shipment',
                'default_related_name': 'productshipment',
            },
        ),
    ]
