# Generated by Django 3.1.3 on 2020-12-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201204_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
