# Generated by Django 3.1.3 on 2020-12-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
