# Generated by Django 3.1.3 on 2020-12-05 11:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201204_2329'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brand',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productattribute',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productmedia',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productshipment',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='producttag',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='specification',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=1, help_text='Unique value for page URL, created from name.', unique=True),
            preserve_default=False,
        ),
    ]
