# Generated by Django 3.0 on 2020-12-05 12:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20201205_1356'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
    ]
