# Generated by Django 3.1.4 on 2020-12-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='logo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='hero',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hero',
            new_name='image',
        ),
    ]
