# Generated by Django 3.1.4 on 2020-12-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20201206_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'default_related_name': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='BrandSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandsuppliers', to='products.brand')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandsuppliers', to='products.supplier')),
            ],
            options={
                'verbose_name': 'brand supplier',
                'verbose_name_plural': 'brand suppliers',
                'default_related_name': 'brandsuppliers',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='suppliers',
            field=models.ManyToManyField(related_name='brands', through='products.BrandSupplier', to='products.Supplier'),
        ),
    ]
