# Generated by Django 3.1.4 on 2020-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20201207_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'default_related_name': 'brands', 'ordering': ['brand_order'], 'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='brandsupplier',
            options={'default_related_name': 'brandsuppliers', 'ordering': ['brand_order'], 'verbose_name': 'brand supplier', 'verbose_name_plural': 'brand suppliers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'categories', 'ordering': ['category_order'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'products', 'ordering': ['product_order'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'default_related_name': 'productmedia', 'ordering': ['media_order'], 'verbose_name': 'product media', 'verbose_name_plural': 'product media'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'default_related_name': 'producttags', 'ordering': ['tag_order'], 'verbose_name': 'product tag', 'verbose_name_plural': 'product tags'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'default_related_name': 'specifications', 'ordering': ['specification_order'], 'verbose_name': 'specification', 'verbose_name_plural': 'specifications'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'ordering': ['tag_order'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='brandsupplier',
            name='brand_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='producttag',
            name='tag_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
