# Generated by Django 3.1.4 on 2020-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20201208_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'default_related_name': 'attributes', 'ordering': ['attribute_order'], 'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'default_related_name': 'productattributes', 'ordering': ['attribute_order'], 'verbose_name': 'product attribute', 'verbose_name_plural': 'product attributes'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'default_related_name': 'productcategories', 'ordering': ['category_order'], 'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'default_related_name': 'suppliers', 'ordering': ['supplier_order'], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='brandsupplier',
            name='brand_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='tag_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
