from .address import getAddressList,getAddress,createAddress,updateAddress,deleteAddress
from .attribute import getAttributeList,getAttribute,createAttribute,updateAttribute,deleteAttribute
from .brand import getBrandList,getBrand,createBrand,updateBrand,deleteBrand
from .category import getCategoryList,getCategory,createCategory,updateCategory,deleteCategory
from .feature import getFeatureList,getFeature,createFeature,updateFeature,deleteFeature
from .hero import getHeroList,getHero,createHero,updateHero,deleteHero
from .logo import getLogoList,getLogo,createLogo,updateLogo,deleteLogo
from .media import getMediaList,getMedia,createMedia,updateMedia,deleteMedia
from .offer import getOfferList,getOffer,createOffer,updateOffer,deleteOffer
from .order import getOrderList,getOrder,createOrder,updateOrder,deleteOrder
from .product import getProductList,getProduct,createProduct,updateProduct,deleteProduct
from .shipment import getShipmentList,getShipment,createShipment,updateShipment,deleteShipment
from .stock import getStockList,getStock,createStock,updateStock,deleteStock
from .supplier import getSupplierList,getSupplier,createSupplier,updateSupplier,deleteSupplier
from .tag import getTagList,getTag,createTag,updateTag,deleteTag
from .warehouse import getWarehouseList,getWarehouse,createWarehouse,updateWarehouse,deleteWarehouse