# Generated by Django 3.1.3 on 2020-12-05 11:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='offer',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
    ]
