# Generated by Django 3.1.4 on 2020-12-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'default_related_name': 'orderstatus', 'verbose_name': 'order status', 'verbose_name_plural': 'orders status'},
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Sent'), (2, 'Cancelled')], default=0),
        ),
    ]
