from django.urls import path


from .views import *

app_name = 'cms'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('categories/',
         CategoryListView.as_view(), name='category-list'),
    path('categories/add/',
         CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/',
         CategoryDetailView.as_view(), name='category-detail'),
    path('categories/update/<int:pk>/',
         CategoryUpdateView.as_view(), name='category-update'),
    path('categories/delete/<int:pk>/',
         CategoryDeleteView.as_view(), name='category-delete'),

    path('tags/',
         TagListView.as_view(), name='tag-list'),
    path('tags/add/',
         TagCreateView.as_view(), name='tag-create'),
    path('tags/<int:pk>/',
         TagDetailView.as_view(), name='tag-detail'),
    path('tags/update/<int:pk>/',
         TagUpdateView.as_view(), name='tag-update'),
    path('tags/delete/<int:pk>/',
         TagDeleteView.as_view(), name='tag-delete'),

    path('attributes/',
         AttributeListView.as_view(), name='attribute-list'),
    path('attributes/add/',
         AttributeCreateView.as_view(), name='attribute-create'),
    path('attributes/<int:pk>/',
         AttributeDetailView.as_view(), name='attribute-detail'),
    path('attributes/update/<int:pk>/',
         AttributeUpdateView.as_view(), name='attribute-update'),
    path('attributes/delete/<int:pk>/',
         AttributeDeleteView.as_view(), name='attribute-delete'),

    path('suppliers/',
         SupplierListView.as_view(), name='supplier-list'),
    path('suppliers/add/',
         SupplierCreateView.as_view(), name='supplier-create'),
    path('suppliers/<int:pk>/',
         SupplierDetailView.as_view(), name='supplier-detail'),
    path('suppliers/update/<int:pk>/',
         SupplierUpdateView.as_view(), name='supplier-update'),
    path('suppliers/delete/<int:pk>/',
         SupplierDeleteView.as_view(), name='supplier-delete'),

    path('warehouses/',
         WareHouseListView.as_view(), name='warehouse-list'),
    path('warehouses/add/',
         WareHouseCreateView.as_view(), name='warehouse-create'),
    path('warehouses/<int:pk>/',
         WareHouseDetailView.as_view(), name='warehouse-detail'),
    path('warehouses/update/<int:pk>/',
         WareHouseUpdateView.as_view(), name='warehouse-update'),
    path('warehouses/delete/<int:pk>/',
         WareHouseDeleteView.as_view(), name='warehouse-delete'),

    path('brands/',
         BrandListView.as_view(), name='brand-list'),
    path('brands/add/',
         BrandCreateView.as_view(), name='brand-create'),
    path('brands/<int:pk>/',
         BrandDetailView.as_view(), name='brand-detail'),
    path('brands/update/<int:pk>/',
         BrandUpdateView.as_view(), name='brand-update'),
    path('brands/delete/<int:pk>/',
         BrandDeleteView.as_view(), name='brand-delete'),

    path('features/',
         FeatureListView.as_view(), name='feature-list'),
    path('features/add/',
         FeatureCreateView.as_view(), name='feature-create'),
    path('features/<int:pk>/',
         FeatureDetailView.as_view(), name='feature-detail'),
    path('features/update/<int:pk>/',
         FeatureUpdateView.as_view(), name='feature-update'),
    path('features/delete/<int:pk>/',
         FeatureDeleteView.as_view(), name='feature-delete'),

    path('products/',
         ProductListView.as_view(), name='product-list'),
    path('products/add/',
         ProductCreateView.as_view(), name='product-create'),
    path('products/<int:pk>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('products/update/<int:pk>/',
         ProductUpdateView.as_view(), name='product-update'),
    path('products/delete/<int:pk>/',
         ProductDeleteView.as_view(), name='product-delete'),

    path('shipments/',
         ShipmentListView.as_view(), name='shipment-list'),
    path('shipments/add/',
         ShipmentCreateView.as_view(), name='shipment-create'),
    path('shipments/<int:pk>/',
         ShipmentDetailView.as_view(), name='shipment-detail'),
    path('shipments/update/<int:pk>/',
         ShipmentUpdateView.as_view(), name='shipment-update'),
    path('shipments/delete/<int:pk>/',
         ShipmentDeleteView.as_view(), name='shipment-delete'),

    path('heroes/',
         HeroListView.as_view(), name='hero-list'),
    path('heroes/add/',
         HeroCreateView.as_view(), name='hero-create'),
    path('heroes/<int:pk>/',
         HeroDetailView.as_view(), name='hero-detail'),
    path('heroes/update/<int:pk>/',
         HeroUpdateView.as_view(), name='hero-update'),
    path('heroes/delete/<int:pk>/',
         HeroDeleteView.as_view(), name='hero-delete'),

    path('offers/',
         OfferListView.as_view(), name='offer-list'),
    path('offers/add/',
         OfferCreateView.as_view(), name='offer-create'),
    path('offers/<int:pk>/',
         OfferDetailView.as_view(), name='offer-detail'),
    path('offers/update/<int:pk>/',
         OfferUpdateView.as_view(), name='offer-update'),
    path('offers/delete/<int:pk>/',
         OfferDeleteView.as_view(), name='offer-delete'),

    path('address/',
         AddressListView.as_view(), name='address-list'),
    path('address/add/',
         AddressCreateView.as_view(), name='address-create'),
    path('address/<int:pk>/',
         AddressDetailView.as_view(), name='address-detail'),
    path('address/update/<int:pk>/',
         AddressUpdateView.as_view(), name='address-update'),
    path('address/delete/<int:pk>/',
         AddressDeleteView.as_view(), name='address-delete'),

    path('orders/',
         OrderListView.as_view(), name='order-list'),
    path('orders/add/',
         OrderCreateView.as_view(), name='order-create'),
    path('orders/<int:pk>/',
         OrderDetailView.as_view(), name='order-detail'),
    path('orders/update/<int:pk>/',
         OrderUpdateView.as_view(), name='order-update'),
    path('orders/delete/<int:pk>/',
         OrderDeleteView.as_view(), name='order-delete'),
    path('model/order/', model_order, name='model-order'),
    path('create_attribute/', create_attribute, name='create-attribute'),
    path('delete_attribute/', delete_attribute, name='delete-attribute'),

    path('create_featurecategory/', create_featurecategory, name='create-featurecategory'),
    path('delete_featurecategory/', delete_featurecategory, name='delete-featurecategory'),
]
